/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import javax.persistence.EntityManager;

import dev.wsollers.repository.CustomEntityManagerFactory;
import dev.wsollers.repository.CitizenRepository;
import dev.wsollers.repository.CitizenJsonRepository;
import dev.wsollers.logging.LogFactory;
import dev.wsollers.repository.QueryTester;

import org.apache.commons.text.WordUtils;

public class App {
  public static void main(String[] args) {
    CitizenRepository citizenRepository = new CitizenJsonRepository();
    citizenRepository.getCitizens();
    LogFactory.testLogger();
    EntityManager em = CustomEntityManagerFactory.getEntityManager();
    QueryTester.testConnection();
    QueryTester.testSqlQuery();
    QueryTester.testQuery();
    QueryTester.testFind();
  }
}
